---
title: "Final Project"
author: "Kanya Kreprasertkul"
date: "4/4/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(tidyverse)
library(dplyr)
library(choroplethr)
library(choroplethrMaps)
library(jsonlite)
library(ggplot2)
library(gridExtra)
library(knitr)
library(kableExtra)
```

```{r}
#download world university ranking data from the website
world_rank <- "https://cwur.org/2019-2020.php" %>%
  read_html() %>%
  html_table(fill = TRUE) %>%
  .[[1]]
```

```{r}
#number of universities in top ranking by country
n_country <- world_rank %>%
  select(Location) %>%
  group_by(Location) %>%
  summarise(total = n()) %>%
  arrange(desc(total))
```

```{r}
#to see top countries in the ranking
result_table <- data.frame(head(n_country, 10))
names(result_table) <- c("Country", "Count")
result_table$Country[1] <- "United States of America"
#use kable to make pretty table
kable(result_table) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

We can see that USA has the highest number of universities in top ranking. So, I want to look into education system in USA.

```{r}
#change column name to be compatible with choroplethr package
names(n_country) <- c("region", "value")
n_country$region <- tolower(n_country$region)
#change some of region name to be compatible with choroplethr package
n_country$region[n_country$region == "usa"] <- "united states of america"
n_country$region[n_country$region == "slovak republic"] <- "slovakia"
n_country$region[n_country$region == "serbia"] <- "republic of serbia"
```

```{r}
#get region data from choroplethrMaps package
data("country.regions")
#merge all regions from choroplethrMaps package and our dataset
n_country <- full_join(n_country, country.regions %>% select(region), by = "region")
n_country$value <- replace_na(n_country$value, 0)
```

```{r, warning = FALSE}
country_choropleth(n_country, title = "The Number of University in Top 2000 Ranking by Country", num_colors = 9)
```

```{r}
#get only ranking of universities in USA
usa_world_rank <- world_rank %>%
  filter(Location == "USA")
```

```{r}
#import dataset from GitHub
salary_potential <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')
salary_potential <- unique(salary_potential)

diversity_school <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
```

```{r}
#import univrsity statistics (downloaded from kaggle)
university_stat <- fromJSON("schoolinfo.json")
#select only important columns
university_stat <- university_stat %>%
  select(`act-avg`, `sat-avg`, `acceptance-rate`, `percent-receiving-aid`, `cost-after-aid`, institutionalControl, tuition, displayName)
```

```{r}
#add percent of diversity
diversity_school <- diversity_school %>%
  mutate(percentage = 100 * enrollment / total_enrollment)
```

```{r}
#remove row containing NA and select only important columns
diversity_school <- diversity_school[!is.na(diversity_school$name), ] %>%
  select(-c("total_enrollment", "enrollment"))
#use spread() to distributes category and percentage
diversity_school2 <- spread(diversity_school, category, percentage) %>%
  select(name, state, White, Black, Hispanic, Asian, Women)
```

```{r}
usa_world_rank2 <- usa_world_rank
usa_world_rank2[(str_detect(usa_world_rank2$Institution, " – ")), ]$Institution <- str_replace(usa_world_rank2[(str_detect(usa_world_rank2$Institution, " – ")), ]$Institution, " – ", " at ")

usa_world_rank2[(str_detect(usa_world_rank2$Institution, " - ")), ]$Institution <- str_replace(usa_world_rank2[(str_detect(usa_world_rank2$Institution, " - ")), ]$Institution, " - ", " at ")

usa_world_rank2[(str_detect(usa_world_rank2$Institution, "–")), ]$Institution <- str_replace(usa_world_rank2[(str_detect(usa_world_rank2$Institution, "–")), ]$Institution, "–", " at ")

usa_world_rank2[(str_detect(usa_world_rank2$Institution, "-")), ]$Institution <- str_replace(usa_world_rank2[(str_detect(usa_world_rank2$Institution, "-")), ]$Institution, "-", " at ")

usa_world_rank2[(str_detect(usa_world_rank2$Institution, ", ")), ]$Institution <- str_replace(usa_world_rank2[(str_detect(usa_world_rank2$Institution, ", ")), ]$Institution, ", ", " at ")
```

```{r}
diversity_school2[(str_detect(diversity_school2$name, " -")), ]$name <- str_replace(diversity_school2[(str_detect(diversity_school2$name, " -")), ]$name, " -", " at ")

diversity_school2[(str_detect(diversity_school2$name, "-")), ]$name <- str_replace(diversity_school2[(str_detect(diversity_school2$name, "-")), ]$name, "-", " at ")
```

```{r}
#change university name (for further inner join)
diversity_school2$name[1264] <- usa_world_rank2$Institution[305]
diversity_school2$name[1751] <- usa_world_rank2$Institution[93]
diversity_school2$name[3562] <- usa_world_rank2$Institution[329]
diversity_school2$name[3642] <- usa_world_rank2$Institution[294]
diversity_school2$name[791] <- usa_world_rank2$Institution[259]
diversity_school2$name[432] <- usa_world_rank2$Institution[238]
diversity_school2$name[794] <- usa_world_rank2$Institution[308]
diversity_school2$name[4196] <- usa_world_rank2$Institution[16]
diversity_school2$name[3939] <- usa_world_rank2$Institution[21]
diversity_school2$name[4179] <- usa_world_rank2$Institution[26]
diversity_school2$name[4351] <- usa_world_rank2$Institution[27]
diversity_school2$name[3055] <- usa_world_rank2$Institution[31]
diversity_school2$name[3952] <- usa_world_rank2$Institution[37]
diversity_school2$name[3155] <- usa_world_rank2$Institution[38]
diversity_school2$name[4123] <- usa_world_rank2$Institution[39]
diversity_school2$name[4176] <- usa_world_rank2$Institution[51]
diversity_school2$name[1753] <- usa_world_rank2$Institution[63]
diversity_school2[(str_detect(diversity_school2$name, "University of Massachusetts")), ]$name <- str_replace(diversity_school2[(str_detect(diversity_school2$name, "University of Massachusetts")), ]$name, " at ", " ")
diversity_school2$name[3671] <- usa_world_rank2$Institution[70]
diversity_school2$name[933] <- usa_world_rank2$Institution[86]
diversity_school2$name[1491] <- usa_world_rank2$Institution[101]
diversity_school2$name[2289] <- usa_world_rank2$Institution[103]
diversity_school2$name[3883] <- usa_world_rank2$Institution[112]
diversity_school2$name[780] <- usa_world_rank2$Institution[127]
diversity_school2$name[2936] <- usa_world_rank2$Institution[139]
diversity_school2$name[4000] <- usa_world_rank2$Institution[151]
diversity_school2$name[3918] <- usa_world_rank2$Institution[167]
diversity_school2$name[802] <- usa_world_rank2$Institution[275]
diversity_school2$name[2089] <- usa_world_rank2$Institution[173]
diversity_school2$name[4379] <- usa_world_rank2$Institution[175]
diversity_school2$name[4035] <- usa_world_rank2$Institution[176]
diversity_school2$name[2464] <- usa_world_rank2$Institution[179]
diversity_school2$name[3552] <- usa_world_rank2$Institution[185]
diversity_school2$name[2754] <- usa_world_rank2$Institution[187]
diversity_school2$name[3914] <- usa_world_rank2$Institution[209]
diversity_school2$name[3689] <- usa_world_rank2$Institution[213]
diversity_school2$name[797] <- usa_world_rank2$Institution[215]
diversity_school2$name[4224] <- usa_world_rank2$Institution[220]
diversity_school2$name[4225] <- usa_world_rank2$Institution[257]
diversity_school2$name[3852] <- usa_world_rank2$Institution[270]
diversity_school2$name[4346] <- usa_world_rank2$Institution[274]
diversity_school2$name[4027] <- usa_world_rank2$Institution[279]
diversity_school2$name[4064] <- usa_world_rank2$Institution[296]
diversity_school2$name[3682] <- usa_world_rank2$Institution[298]
usa_world_rank2 <- data.frame(rbind(usa_world_rank2, usa_world_rank2[304, ]))
usa_world_rank2$Institution[304] <- diversity_school2$name[3319]
usa_world_rank2$Institution[359] <- diversity_school2$name[885]
diversity_school2$name[3917] <- usa_world_rank2$Institution[319]
diversity_school2$name[4530] <- usa_world_rank2$Institution[322]
diversity_school2$name[4071] <- usa_world_rank2$Institution[325]
diversity_school2$name[1371] <- usa_world_rank2$Institution[327]
diversity_school2$name[2824] <- usa_world_rank2$Institution[328]
diversity_school2$name[3953] <- usa_world_rank2$Institution[335]
diversity_school2$name[3688] <- usa_world_rank2$Institution[336]
diversity_school2$name[2758] <- usa_world_rank2$Institution[345]
diversity_school2$name[3460] <- usa_world_rank2$Institution[346]
```

```{r}
#diversity_school2[(str_detect(diversity_school2$name, "University of California")), ]$name <- str_replace(diversity_school2[(str_detect(diversity_school2$name, "University of California")), ]$name, " at ", ", ")
```

```{r}
diversity_school2[str_detect(diversity_school2$name, "Saint Benedict"), ]
diversity_school2[str_detect(diversity_school2$name, "SUNY"), ]
usa_world_rank2[str_detect(usa_world_rank2$Institution, "SUNY"), ]


which(str_detect(diversity_school2$name, "Simmons College") == TRUE)
which(str_detect(usa_world_rank2$Institution, "Simmons University") == TRUE)
```


```{r}
#usa_world_rank2 <- usa_world_rank2 %>% arrange(Institution)
setdiff(usa_world_rank2$Institution, diversity_school2$name)
#there are 17 universities that are not included in the diversity_school data
```

```{r}
rank_diversity_df <- inner_join(diversity_school2, usa_world_rank2, by = c("name" = "Institution")) %>%
  arrange(National.Rank) %>%
  mutate(Men = 100 - Women)
```

```{r}
university_stat2 <- university_stat
university_stat2[(str_detect(university_stat2$displayName, "--")), ]$displayName <- str_replace(university_stat2[(str_detect(university_stat2$displayName, "--")), ]$displayName, "--", " at ")
```

```{r}
#change university name (for further inner join)
university_stat2$displayName[60] <- rank_diversity_df$name[16]
university_stat2$displayName[53] <- rank_diversity_df$name[17]
university_stat2$displayName[44] <- rank_diversity_df$name[21]
university_stat2$displayName[52] <- rank_diversity_df$name[31]
university_stat2$displayName[54] <- rank_diversity_df$name[36]
university_stat2$displayName[92] <- rank_diversity_df$name[37]
university_stat2$displayName[57] <- rank_diversity_df$name[38]
university_stat2$displayName[193] <- rank_diversity_df$name[89]
university_stat2$displayName[90] <- rank_diversity_df$name[61]
university_stat2$displayName[77] <- rank_diversity_df$name[63]
university_stat2$displayName[115] <- rank_diversity_df$name[64]
university_stat2$displayName[84] <- rank_diversity_df$name[66]
university_stat2$displayName[123] <- rank_diversity_df$name[67]
university_stat2$displayName[98] <- rank_diversity_df$name[68]
university_stat2$displayName[100] <- rank_diversity_df$name[90]
university_stat2$displayName[102] <- rank_diversity_df$name[92]
```

```{r}
rank_diversity_df <- left_join(rank_diversity_df, university_stat2, by = c("name" = "displayName")) 
```

```{r}
#change name of the university to be the official name
rank_diversity_df$name[6] <- "University of California, Berkeley"
rank_diversity_df$name[13] <- "University of California, Los Angeles"
rank_diversity_df$name[14] <- "University of Michigan, Ann Arbor"
rank_diversity_df$name[16] <- "University of Washington"
rank_diversity_df$name[17] <- "University of Illinois at Urbana-Champaign"
rank_diversity_df$name[19] <- "University of Wisconsin-Madison"
rank_diversity_df$name[23] <- "University of California, San Francisco"
rank_diversity_df$name[25] <- "University of Minnesota"
rank_diversity_df$name[32] <- "Rutgers University-New Brunswick"
rank_diversity_df$name[34] <- "University of California, Davis"
rank_diversity_df$name[40] <- "University of California, Irvine"
rank_diversity_df$name[41] <- "University of California, Santa Barbara"
rank_diversity_df$name[48] <- "Texas A&M University"
rank_diversity_df$name[53] <- "University of Maryland"
rank_diversity_df$name[67] <- "University of Missouri"
rank_diversity_df$name[72] <- "University of California, Riverside"
rank_diversity_df$name[75] <- "University of California, Santa Cruz"
rank_diversity_df$name[86] <- "University of Maryland, Baltimore"
rank_diversity_df$name[89] <- "Indiana University-Purdue University Indianapolis"
rank_diversity_df$name[92] <- "University of Tennessee"
```

```{r}
#scale percentage to 100%
rank_diversity_df <- rank_diversity_df %>%
  mutate(total = White + Black + Hispanic + Asian) %>%
  mutate(White2 = White * 100 / total, Black2 = Black * 100 / total, Hispanic2 = Hispanic * 100 / total, Asian2 = Asian * 100 / total)
```

```{r}
#gather by race
rank_diversity_df2 <- gather(rank_diversity_df, key = "Race", value = value, White2, Black2, Hispanic2, Asian2) %>% arrange(National.Rank)
rank_diversity_df2$Race <- str_replace(rank_diversity_df2$Race, "2", "")
```

```{r, fig.width = 8, fig.height = 8}
#use ggplot2 barplot to demonstrate the percentage of diversity
axis_lable1 <- c(rank_diversity_df$name[1:49])
axis_lable1 <- axis_lable1[order(-1:-49)]
ggplot(data = rank_diversity_df2[1:196, ], aes(x = name, y = value, fill = Race)) + geom_bar(stat = "identity") + coord_flip() + scale_x_discrete(limits = axis_lable1) + xlab("Institution") + ylab("Diversity Percentage") + ggtitle("Diversity Percentage of University in 1-50 Ranking") + theme(axis.title.x = element_blank(), axis.title.y = element_blank())

axis_lable2 <- c(rank_diversity_df$name[50:96])
axis_lable2 <- axis_lable2[order(-1:-47)]
ggplot(data = rank_diversity_df2[197:384, ], aes(x = name, y = value, fill = Race)) + geom_bar(stat = "identity") + coord_flip() + scale_x_discrete(limits = axis_lable2) + xlab("Institution") + ylab("Diversity Percentage") + ggtitle("Diversity Percentage of University in 51-100 Ranking") + theme(axis.title.x = element_blank(), axis.title.y = element_blank())
```

```{r, fig.width = 8, fig.height = 8}
#gather by sex
rank_diversity_df3 <- gather(rank_diversity_df, key = "Sex", value = value, Men, Women) %>%
  arrange(National.Rank)

ggplot(data = rank_diversity_df3[1:98, ], aes(x = name, y = value, fill = Sex)) + geom_bar(stat = "identity") + coord_flip() + scale_x_discrete(limits = axis_lable1) + xlab("Institution") + ylab("Sex Ratio") + ggtitle("Sex Ratio of University in 1-50 Ranking") + scale_fill_brewer(palette = "Paired") + theme(axis.title.x = element_blank(), axis.title.y = element_blank())

ggplot(data = rank_diversity_df3[99:192, ], aes(x = name, y = value, fill = Sex)) + geom_bar(stat = "identity") + coord_flip() + scale_x_discrete(limits = axis_lable2) + xlab("Institution") + ylab("Sex Ratio") + ggtitle("Sex Ratio of University in 51-100 Ranking") + scale_fill_brewer(palette = "Paired") + theme(axis.title.x = element_blank(), axis.title.y = element_blank())
```

```{r}
which(is.na(rank_diversity_df$`acceptance-rate`[1:96]) == TRUE)
#there are 8 universities that do not have acceptance rate and tuition fee

rank_diversity_df$`percent-receiving-aid`
```

```{r, warning = FALSE, fig.width = 8, fig.height = 6}

f1 <- ggplot(data = top100Data, aes(x = National.Rank, y = `acceptance-rate`)) + geom_point() + xlab("National Ranking") + ylab("Acceptance Rate") + stat_smooth(method = "lm", formula = y ~ x, size = 1)

f2 <- ggplot(data = top100Data, aes(x = National.Rank, y = tuition)) + geom_point() + xlab("National Ranking") + ylab("Tuition Fee") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

f3 <- ggplot(data = top100Data, aes(x = National.Rank, y = `percent-receiving-aid`)) + geom_point() + xlab("National Ranking") + ylab("Percent Receiving Aid") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

f4 <- ggplot(data = top100Data, aes(x = National.Rank, y = `cost-after-aid`)) + geom_point() + xlab("National Ranking") + ylab("Tution Fee (after receiving aid)") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

grid.arrange(f1, f2, ncol = 1)
grid.arrange(f3, f4, ncol = 1)
```





```{r}
salary_potential2 <- salary_potential
```

```{r}
#change university name (for further inner join)
salary_potential2$name[574] <- rank_diversity_df$name[4]
salary_potential2$name[61] <- rank_diversity_df$name[6]
salary_potential2$name[69] <- rank_diversity_df$name[13]
salary_potential2$name[64] <- rank_diversity_df$name[21]
salary_potential2$name[73] <- rank_diversity_df$name[34]
salary_potential2$name[70] <- rank_diversity_df$name[40]
salary_potential2$name[68] <- rank_diversity_df$name[41]
salary_potential2$name[867] <- rank_diversity_df$name[16]
salary_potential2$name[404] <- rank_diversity_df$name[14]
salary_potential2$name[795] <- rank_diversity_df$name[22]
salary_potential2$name[430] <- rank_diversity_df$name[25]
salary_potential2$name[797] <- rank_diversity_df$name[70]
salary_potential2$name[467] <- rank_diversity_df$name[27]
salary_potential2$name[708] <- rank_diversity_df$name[31]
salary_potential2$name[843] <- rank_diversity_df$name[35]
salary_potential2$name[633] <- rank_diversity_df$name[36]
salary_potential2$name[215] <- rank_diversity_df$name[38]
salary_potential2$name[225] <- rank_diversity_df$name[89]
salary_potential2$name[715] <- rank_diversity_df$name[39]
salary_potential2$name[149] <- rank_diversity_df$name[45]
salary_potential2$name[794] <- rank_diversity_df$name[48]
salary_potential2$name[355] <- rank_diversity_df$name[53]
salary_potential2$name[220] <- rank_diversity_df$name[61]
salary_potential2$name[397] <- rank_diversity_df$name[63]
salary_potential2$name[31] <- rank_diversity_df$name[64]
salary_potential2$name[593] <- rank_diversity_df$name[66]
salary_potential2$name[468] <- rank_diversity_df$name[67]
salary_potential2$name[797] <- rank_diversity_df$name[70]
salary_potential2$name[635] <- rank_diversity_df$name[81]
salary_potential2$name[85] <- rank_diversity_df$name[82]
salary_potential2$name[844] <- rank_diversity_df$name[91]
salary_potential2$name[773] <- rank_diversity_df$name[92]
salary_potential2$name[561] <- rank_diversity_df$name[93]
salary_potential2$name[133] <- rank_diversity_df$name[95]
```

```{r}
salary_potential2[str_detect(salary_potential2$name, "University of South Florida"), ]
rank_diversity_df[str_detect(rank_diversity_df$name, "University of South Florida"), ]

which(str_detect(salary_potential2$name, "University of South Florida") == TRUE)
which(str_detect(rank_diversity_df$name, "University of South Florida") == TRUE)

salary_potential2$name[133]
rank_diversity_df$name[95]
```

```{r}
# compare these 2 first because only a few rows needed to change
setdiff(university_stat2$displayName, diversity_school2$name)
#50
setdiff(rank_diversity_df$name[1:96], university_stat2$displayName)
```

```{r}
# 8 
setdiff(rank_diversity_df$name[1:96], salary_potential2$name)
names(rank_diversity_df)
```

```{r}
rank_diversity_df <- left_join(rank_diversity_df, salary_potential2, by = c("name" = "name")) %>%
  select(-c("Location", "Quality.of.Education", "Alumni.Employment", "Quality.of.Faculty", "Research.Performance", "Score", "rank", "state_name"))
top100Data <- rank_diversity_df[1:96, ]
```

```{r}
#write dataframe to csv file
write.csv(top100Data, "top100Data.csv", row.names = FALSE)
```

```{r, warning = FALSE, fig.width = 8, fig.height = 6}
#rank_diversity_df$stem_percent

#1-50 Ranking
f5 <- ggplot(data = top100Data, aes(x = National.Rank, y = early_career_pay)) + geom_point() + xlab("National Ranking") + ylab("Early Career Pay") + stat_smooth(method = "lm", formula = y ~ x, size = 1)

f6 <- ggplot(data = top100Data, aes(x = National.Rank, y = mid_career_pay)) + geom_point() + xlab("National Ranking") + ylab("Mid Career Pay") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

grid.arrange(f5, f6, ncol = 1)
```


```{r, fig.width = 8, fig.height = 6}

f7 <- ggplot(data = top100Data, aes(x = National.Rank, y = stem_percent)) + geom_point() + xlab("National Ranking") + ylab("STEM Percentage") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

f8 <- ggplot(data = top100Data, aes(x = National.Rank, y = make_world_better_percent)) + geom_point() + xlab("National Ranking") + ylab("Make World Better Percentage") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

grid.arrange(f7, f8, ncol = 1)
```


```{r, fig.width = 8, fig.height = 6}
#top100Data$`sat-avg`
f9 <- ggplot(data = top100Data, aes(x = National.Rank, y = `act-avg`)) + geom_point() + xlab("National Ranking") + ylab("Average ACT Score") + stat_smooth(method = "lm", formula = y ~ x, size = 1)

f10 <- ggplot(data = top100Data, aes(x = National.Rank, y = `sat-avg`)) + geom_point() + xlab("National Ranking") + ylab("Average SAT Score") + stat_smooth(method = "lm", formula = y ~ x, size = 1)  

grid.arrange(f9, f10, ncol = 1)
```

```{r}
#, fig.width = 8, fig.height = 6
#manually fill NA
top100Data$institutionalControl[23] <- "public"
top100Data$institutionalControl[26] <- "public"
top100Data$institutionalControl[50] <- "public"
top100Data$institutionalControl[56] <- "private"
top100Data$institutionalControl[60] <- "private"
top100Data$institutionalControl[70] <- "public"
top100Data$institutionalControl[77] <- "public"
top100Data$institutionalControl[86] <- "public"

school_type <- top100Data %>% 
  select(institutionalControl, tuition, `percent-receiving-aid`) %>% 
  group_by(institutionalControl) %>% 
  summarise(
    Count = n(),
    Average_Tuition = mean(tuition, na.rm = TRUE),
    Average_Aid = mean(`percent-receiving-aid`, na.rm = TRUE)
  ) 
  
school_type$institutionalControl[1] <- "Private"
school_type$institutionalControl[2] <- "Public"
school_type$Average_Tuition <- formatC(school_type$Average_Tuition / 1000, digits = 2, format = "f")
school_type$Average_Aid <- formatC(school_type$Average_Aid, digits = 2, format = "f")

#school_type <- gather(school_type, key = "Variable", value = value, Count, Average_Tuition, Average_Aid)

ggplot(data = school_type, aes(x = Variable, y = value, fill = institutionalControl)) +
geom_bar(stat = "identity", position = position_dodge())

f11 <- ggplot(school_type, aes(x = institutionalControl, y = Count)) + geom_bar(stat = "identity") + xlab("University Type") + ylab("Count") + geom_text(aes(label = Count), vjust = 1.6, color = "white", size = 5) + theme_light(base_size = 15)

f12 <- ggplot(school_type, aes(x = institutionalControl, y = Average_Tuition)) + geom_bar(stat = "identity") + xlab("University Type") + ylab("Tuition Fee (in thousand)") + geom_text(aes(label = Average_Tuition), vjust = 1.6, color = "white", size = 5) + theme_light(base_size = 15)

f13 <- ggplot(school_type, aes(x = institutionalControl, y = Average_Aid)) + geom_bar(stat = "identity") + xlab("University Type") + ylab("Average of Receiving Aid") + geom_text(aes(label = Average_Aid), vjust = 1.6, color = "white", size = 5) + theme_light(base_size = 15)

grid.arrange(f11, f12, f13, ncol = 3)
```


```{r, fig.width = 8, fig.height = 6}
f14 <- ggplot(data = top100Data, aes(x = National.Rank, y = tuition, color = institutionalControl)) + geom_point() + xlab("National Ranking") + ylab("Tuition Fee") + scale_colour_discrete(name = "University Type", labels = c("Private", "Public")) 

f15 <- ggplot(data = top100Data, aes(x = National.Rank, y = `percent-receiving-aid`, color = institutionalControl)) + geom_point() + xlab("National Ranking") + ylab("Percent Receiving Aid") + scale_colour_discrete(name = "University Type", labels = c("Private", "Public"))  

grid.arrange(f14, f15, ncol = 1)
#top100Data$institutionalControl
```



```{r}


#top100Data$National.Rank
```


```{r}
count_state <- rank_diversity_df[1:96, ] %>%
  select(state.x) %>%
  group_by(state.x) %>%
  summarise(value = n()) %>%
  arrange(desc(value))
```

```{r}
#to see top state
result_table2 <- data.frame(head(count_state, 10))
names(result_table2) <- c("State", "Count")
#
kable(result_table2) %>%
  kable_styling(bootstrap_options = "striped", full_width = F)
```

```{r}
data(continental_us_states)
names(count_state)[1] <- "region"
count_state$region <- tolower(count_state$region)
count_state$region[count_state$region == "washington"] <- "district of columbia"
count_state2 <- data.frame(continental_us_states)
names(count_state2)[1] <- "region"
count_state2 <- left_join(count_state2, count_state, key = c("region" = "region"))
count_state2$value <- replace_na(count_state2$value, 0)
```

```{r}
state_choropleth(count_state2, title  = "The Number of University in Top 100 USA Ranking by State", zoom = continental_us_states)
```



